### ISSUE TITLE
dist folder not created for npm build

### ISSUE THREAD

**Issue by ittechsathish** [onixjs/starter#2]
"scripts": {
    "build": "npm run clean && npm run lint:fix",
    "start": "npm run build && node dist/index.js",
    "clean": "del dist dist6",
    "lint": "npm run prettier:check",
    "lint:fix": "npm run prettier:fix",
    "prettier:cli": "prettier \"**/*.ts\" \"**/*.js\"",
    "prettier:check": "npm run prettier:cli -- -l",
    "prettier:fix": "npm run prettier:cli -- --write"
  },

With the above script in windows, npm run build is not creating dist folder.

**Comment by jonathan-casarrubias** [comment]
@ittechsathish thanks for reaching out,

Hey so I think this build script is incomplete, it won't be creating the source since the tsc part is not there

https://github.com/onixjs/starter/blob/master/package.json#L7

it should be something like

```json
{
  "scripts": {
    "build": "npm run clean && npm run lint:fix && ./node_modules/.bin/tsc"
  }
}
```

./node_modules/.bin/tsc is the part that will create the dist directory

**Comment by jonathan-casarrubias** [comment]
@ittechsathish try version 1.0.2 of this starter by pulling the latest change and verify if @kattsushi's fix works.

Cheers
Jon

**Comment by jonathan-casarrubias** [comment]
@ittechsathish try version 1.0.2 of this starter by pulling the latest change and verify if @kattsushi's fix works.

Cheers
Jon

**Comment by ittechsathish** [comment]
New version also not working.
Please verify.

dist folder also not created.

> npm start 
> @onixjs/starter@1.0.2 start C:\Users\sveerakumar\Documents\onix-study
> npm run build && node dist/index.js


> @onixjs/starter@1.0.2 build C:\Users\sveerakumar\Documents\onix-study
> npm run lint:fix && node_modules/.bin/tsc


> @onixjs/starter@1.0.2 lint:fix C:\Users\sveerakumar\Documents\onix-study
> npm run prettier:fix


> @onixjs/starter@1.0.2 prettier:fix C:\Users\sveerakumar\Documents\onix-study
> npm run prettier:cli -- --write


> @onixjs/starter@1.0.2 prettier:cli C:\Users\sveerakumar\Documents\onix-study
> prettier "**/*.ts" "**/*.js" "--write"

src\example.app\example.component.ts 496ms
src\example.app\example.model.ts 13ms
src\example.app\example.module.ts 10ms
src\example.app\index.ts 11ms
src\example.app\mongo.datasource.ts 19ms
src\index.ts 20ms
'node_modules' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @onixjs/starter@1.0.2 build: `npm run lint:fix && node_modules/.bin/tsc`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @onixjs/starter@1.0.2 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sveerakumar\AppData\Roaming\npm-cache\_logs\2018-05-10T10_08_16_448Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @onixjs/starter@1.0.2 start: `npm run build && node dist/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @onixjs/starter@1.0.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sveerakumar\AppData\Roaming\npm-cache\_logs\2018-05-10T10_08_16_548Z-debug.log

**Comment by jonathan-casarrubias** [comment]
Would you mind to try the latest I published, that should work if still is not, just install typescript globally


Npm install -g typescript


Cheers
Jon

**Comment by ittechsathish** [comment]
It is working Thanks

**Comment by jonathan-casarrubias** [comment]
@ittechsathish awesome, I was blindly trying to fix that but I was pretty sure the latest publish should work...

I really appreciate you early testing the framework, don't hesitate to report any other issue you might find or even any improvement.

We are very close to beta, I'm just trying to fix a couple of performance issues related to disconnections and unsubscriptions, hopefully, when I fix those I will be publishing the beta version, so having people like you trying out and providing feedback will be much appreciated

For now I'm closing this 2 issues...

Cheers
Jon

**Comment by Hussi503** [comment]
Still im not getting that dist folder generating. could pelase help me to resolve we are self hosted agent on azure devops and deploying through pipeline. but when we run locally npm run build: azure the dist folder is created.
